### ISSUE TITLE
`DuplicateRouteDetector` has no tests 😱

### ISSUE THREAD

**Issue by gsteel** [mezzio/mezzio-router#47]

**Comment by boesing** [comment]
Its indirectly tested via the `RouteCollectorTest` tho.
https://github.com/mezzio/mezzio-router/commit/bb9bce25a998b66666e58c7924a2b5bdb63a2de5

Not saying it should be like this, just that it is kinda tested. But TBH, the whole class should have been `@internal` as I would not expect that this is a service we should provide without an interface.

**Comment by gsteel** [comment]
Yes, I since noticed the indirect tests - I ran coverage locally and it came out at 0% because of the `#[CoversClass]` on the collector test case. I'll add an issue to mark it as internal for `4.0.0`

**Comment by gsteel** [comment]
Closed via #67
