### ISSUE TITLE
[RFC] Add `RouteInterface` and `RouteResultInterface`

### ISSUE THREAD

**Issue by ghostwriter** [mezzio/mezzio-router#74]
### Feature Request

For v4

- [ ] Add `RouteInterface`, `RouteResultInterface`, and any other additional interfaces
- [ ] Update `RouterInterface`, `RouteCollectorInterface`, and make sure all the `final` classes implement these interfaces.

helps with the use of mocks in testing.

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | yes

#### Summary

eg.

```diff
+ interface RouteInterface extends \Psr\Http\Server\MiddlewareInterface {
+    public function getPath(): string;
+    public function getName(): string;
+    public function getMiddleware(): \Psr\Http\Server\MiddlewareInterface;
+    public function getAllowedMethods(): ?array;
+    public function allowsMethod(string $method): bool;
+    public function allowsAnyMethod(): bool;
+    public function setOptions(array $options): void;
+    public function getOptions(): array;
+}

+ interface RouteResultInterface extends MiddlewareInterface
+ {
+    /**
+     * Does the result represent successful routing?
+     */
+    public function isSuccess(): bool;
+
+    /**
+     * Retrieve the route that resulted in the route match.
+     *
+     * @return false|RouteInterface false if representing a routing failure; Route instance otherwise.
+     */
+    public function getMatchedRoute();
+
+    /**
+     * Retrieve the matched route name, if possible.
+     *
+     * If this result represents a failure, return false; otherwise, return the
+     * matched route name.
+     *
+     * @return false|string
+     */
+    public function getMatchedRouteName();
+
+    /**
+     * Returns the matched params.
+     *
+     * Guaranteed to return an array, even if it is simply empty.
+     *
+     * @return array<string, mixed>
+     */
+    public function getMatchedParams(): array;
+
+    /**
+     * Is this a routing failure result?
+     */
+    public function isFailure(): bool;
+    /**
+     * Does the result represent failure to route due to HTTP method?
+     */
+    public function isMethodFailure(): bool;
+
+    /**
+     * Retrieve the allowed methods for the route failure.
+     *
+    * @return null|list<string> HTTP methods allowed
+     */
+    public function getAllowedMethods(): ?array;
+ }

interface RouteCollectorInterface
{
    /**
-     * @return list<Route>
+     * @return list<RouteInterface>
     */
    public function getRoutes(): array;

-    public function match(\Psr\Http\Message\ServerRequestInterface $request): RouteResult;
+    public function match(\Psr\Http\Message\ServerRequestInterface $request): RouteResultInterface;

-   public function *(string $path, MiddlewareInterface $middleware, ?string $name = null): Route;
+   public function *(string $path, MiddlewareInterface $middleware, ?string $name = null): RouteInterface;
}

interface RouterInterface
{
-    public function addRoute(Route $route): void;
+    public function addRoute(RouteInterface $route): void;
}
```

**Comment by gsteel** [comment]
Not against the idea, but it is trivial to create a concrete `RouteResult` for tests and the named constructors are part of the public api.

```php
$routeResult = RouteResult::fromRoute(
    new Route('/', new NoOpMiddleware()),
);
$failureResult = RouteResult::fromRouteFailure(['GET', 'POST']);
```

It's also pretty straightforward to generate concrete routes too.

Furthermore, you shouldn't really mock what you don't own…

**Comment by ghostwriter** [comment]
I agree, 

**The comment about mocks, was just an additional benefit.**

I'm trying to build a testing library for mezzio applications.

for example, If i wanted to test `Router` class, I can wrap that `final` class with a custom class that also implemented the same interface `RouterInterface` so i can return `TestBenchRouter` instead of `Router` class.

```php
<?php

final readonly class TestBenchRouter implements RouterInterface
{
    public function __construct(
        private RouterInterface $router,
    ) {
    }

    #[Override]
    public function addRoute(Route $route): void
    {
        $this->router->addRoute($route);
    }

    #[Override]
    public function generateUri(string $name, array $substitutions = [], array $options = []): string
    {
        return $this->router->generateUri($name, $substitutions, $options);
    }

    #[Override]
    public function match(Request $request): RouteResult
    {
        return $this->router->match($request);
    }
}

function test(RouterInterface $router): void {}

test(new Router);
test(new TestBenchRouter);
```

However, we can not do the same with `RouteResult`

```php
final class RouteResult {}

function test(RouteResult $router): void {}
```

**Comment by ghostwriter** [comment]
<img width="526" alt="image" src="https://github.com/user-attachments/assets/90f6f9bb-a552-47e4-adca-f18c7d806ad4">

**Comment by gsteel** [comment]
I'm still on the fence as I consider these two value objects

It's worth having this discussion right now though because there's not much left to do for a v4 release as far as I can tell.

Paging @mezzio/technical-steering-committee for more input

**Comment by froschdesign** [comment]
These are value objects:

https://github.com/mezzio/mezzio-router/blob/40906eb2bcc5acea712946271319eff9aad18875/src/Route.php#L21-L36

https://github.com/mezzio/mezzio-router/blob/40906eb2bcc5acea712946271319eff9aad18875/src/RouteResult.php#L14-L34

**Comment by ghostwriter** [comment]
I understand, and I’m not disagreeing with you.

If we need different implementations of the value object, to be swapped out or used interchangeably, an interface is needed.

Is there a reason that a value object can/should **not** have interface?

**Comment by gsteel** [comment]
The reason a value object doesn't generally need an interface is because it should be a pure/immutable struct that is easy to create - it doesn't have behaviour, it's a value - like returning an `int`, but with more semantics. There's no need to mock it - your mock or stub should just return the concrete value that you have fixed as part of the test suite.

Why whould you need a different implementation? If there are things that you want these value objects to do, beyond what they were designed for, then it'd be better to talk about that.

I acknowledge btw that `Route` is not immutable because it allows the `name` and `options` to be mutated - this should possibly be fixed.

**Comment by ghostwriter** [comment]
> Why whould you need a different implementation? If there are things that you want these value objects to do, beyond what they were designed for, then it'd be better to talk about that.

yes, I would like to be able to wrap the objects and add additional assertion methods on them.

```php
<?php
function test(Request $request, RouterInterface $router): void
{
  if($request instanceof TestBenchRequest){
     $request->assertServerRequestMethod(RequestMethodInterface::METHOD_GET)
     $request->assertServerRequestUriPath('/')
  }

  if($router instanceof TestBenchRouter){
     $router->assertHasRouteName('home');

     $routeResult = $router->match($request); // RouteResult
      if($routeResult instanceof TestBenchRouteResult){
          $routeResult->assertRouteName('home');
      }
  }
}

test(new TestBenchRequest(new Request), new TestBenchRouter(new Router));
```

**Comment by weierophinney** [comment]
@ghostwriter You're doing branching in your test based on the returned type, which is going to lead to brittle tests.

If you consider the `RouteResult` as a value object, you could instead add assertions that accept the `RouteResult` as an argument, and assert conditions on them:

```php
$this->assertRouteResultName($routeResult, 'home');
```

This route allows you to write the code as a PHPUnit assertion instead, and means you don't need to mock the result. This also has the benefit that if you want to do E2E testing, you don't can use an actual router instance instead of a mock.

**Comment by ghostwriter** [comment]
Thanks for your input @weierophinney,

> You're doing branching in your test based on the returned type, which is going to lead to brittle tests.

Correction this was just an example code to show the kinds of additional methods I wanted to add.

Sorry for the confusion.

I’m not doing any branching in the actual tests.

I'm doing Integration testing using the actual router instance.

- load the container
- create the application
- load the pipeline
- load the routes
- dispatch a request
- collect and assert (container, router, routeResult, request, response)

I am not using any mocks.

--- 
> If you consider the `RouteResult` as a value object, you could instead add assertions that accept the `RouteResult` as an argument, and assert conditions on them

You are absolutely right, again i agree with what you all are saying.

I still think we need the interface.

(eg. Test that a method on a `final` class, `RouteResult`, was called by `Middleware`)

--- 

```php
$routeResult->assertRouteResultName('home');

// ^ this above code is calling (internally)

$this->assertRouteResultName($routeResult, 'home');

// Using a Constraint class that accepts a request/response/object then recursively calling constraints
```

---

<details><summary> wip </summary>
<p>

<img width="800" alt="image" src="https://github.com/user-attachments/assets/25d4b2dd-68bf-477d-b984-de5b1addb09f">

<img width="800" alt="image" src="https://github.com/user-attachments/assets/b14b12d6-9c03-4171-96f8-b190e02a7868">

</p>
</details>

**Comment by ghostwriter** [comment]
I have a custom Middleware for collecting information.

During the application creation process, the step I mentioned above.

Before loading the pipeline, I pass my custom middleware.

This custom middleware passes itself as the final RequestHandler for each middleware.

after each middleware is processed it can collect information about what changed (diff).

I was using the delegation pattern to compose objects with predefined assertions methods.

Before the classes were **not** `final` so I _misused_ inheritance (extending the classes).

Now that classes are `final` it requires an interface, to properly use the delegations pattern.

**Comment by ghostwriter** [comment]
I think the "value object" argument should only apply when the value object only has one value. (`Email`)

when it has multiple values, we need a contract to define how we can access the other values. (`Order`)

**Comment by weierophinney** [comment]
I think I need to see how you would _like_ to interact with it first, and what E2E workflow you're trying to test. We can argue back and forth about syntax all day, but if you're not sharing exactly waht you're trying to accomplish, we'll go in circles.

-----

Getting beyond the semantics of whether or not it's a value object, the main point here is that a `RouteResult` is _immutable_; it encapsulates a specific state. A mocking library allows you to ... create a specific state. The point that myself and others are trying to make here is that you can instruct your router mock to return a specific route result, representing the expected state to test against. This doesn't require mocking, just an instance. Typically, you are not going to be concerned with what methods are called on it, but rather what the _consumer_ of the RouteResult does with it, given a specific state.

Immutable state objects generally don't need mocking; you just create an instance with the desired state and instruct _other_ mocks to consume or produce them.

So, share the test case you'd like to enable. This will allow us to decide if this is best handled by a new interface, or if we can suggest an alternative that will let you accomplish your goals without introducing it.

**Comment by ghostwriter** [comment]
> I think I need to see how you would like to interact with it first, and what E2E workflow you're trying to test. We can argue back and forth about syntax all day, but if you're not sharing exactly waht you're trying to accomplish, we'll go in circles.

agreed.

To be clear… I’m not arguing.

I'm perfectly okay with a, `no` response.

I repeatedly explain myself to be thorough, to see if any of the additional context i may have in my head would change things.

I wanted to understand why, "no",  so i can educate myself and apply that new understanding in my own work.

I cannot learn anything from "the maintainers said no".

---

> A mocking library allows you to ... create a specific state. The point that myself and others are trying to make here is that you can instruct your router mock to return a specific route result, representing the expected state to test against. 

Here is the disconnect, **I am not trying to mock anything**.

I want the application to compose and run the same exact way it does in production

Calling `$this->get('/')` is **Identical** to visiting `public/index.php`.

<img width="622" alt="image" src="https://github.com/user-attachments/assets/df82adfc-c4fc-42ac-9914-af5f4ab1448c">

The only difference is that when we are in a testing environment `$_ENV['testing'] `, 
we add a custom middleware 

```php
if (isset($_ENV['testing']) && $_ENV['testing']) {
    // Register custom middleware for testing
    $app->pipe(new TestBenchMiddleware());
}
```

…that wraps the objects in our custom psr and mezzio compliant delegator classes that add extra behaviors to these objects.

eg.

```php
final readonly class TestBenchMiddleware implements MiddlewareInterface
{
    public function process(ServerRequestInterface $request, RequestHandlerInterface $handler): ResponseInterface
    {
        // Check if the request is an instance of TestBenchServerRequest
        if (!$request instanceof TestBenchServerRequest) {
            // Wrap the request in a TestBenchServerRequest
            $request = new TestBenchServerRequest($request);
        }

        $routeResult = $request->getAttribute(RouteResult::class);
        // Check if the route result is an instance of TestBenchRouteResult
        if (!$routeResult instanceof TestBenchRouteResult && $routeResult instanceof RouteResult) {
            // Wrap the route result in a TestBenchRouteResult
            $routeResult = new TestBenchRouteResult($routeResult);
            // Set the route result as an attribute of the request
            $request = $request->withAttribute(RouteResult::class, $routeResult);
        }

        // Check if the handler is an instance of TestBenchRequestHandler
        if (!$handler instanceof TestBenchRequestHandler) {
            // Wrap the handler in a TestBenchRequestHandler
            $handler = new TestBenchRequestHandler($handler);
        }

        // Pass the modified or original request to the next handler
        return $handler->handle($request);
    }
}
```

The `TestBenchRouteResult` part will not work in v4, because `RouteResult` is  `final`, i was previously incorrectly extending from this class.

So anywhere `RouteResult` is used we will not be able to pass a wrapped `TestBenchRouteResult`.

If there was a `RouteResultInterface`, we would be able to pass a wrapped `TestBenchRouteResult` or `RouteResult`.

> This doesn't require mocking, just an instance. Typically, you are not going to be concerned with what methods are called on it, but rather what the consumer of the RouteResult does with it, given a specific state.

I want to test the objects the application creates at runtime, not what the user manual define or pass in during testing.

**Comment by gsteel** [comment]
So, the point here is testing expectations - you expect the router to match a specific route and if it doesn't, there's a problem with your route configuration. Your wrapped `RouterInterface` will yield the `RouteResult` you expect _(hopefully)_. None of the middleware in the pipeline should alter the matched route - that would be very weird, so, because requests are immutable, you can be sure that the route result referenced in the request is what the router implementation returned. Instead of "newing" all these wrappers, wouldn't it be better to inject them into the testing framework in some way, so that users can say to the 'TestRouter' for example, `$testRouter->expectMatchedRouteName('foo')` prior to executing the pipeline? It doesn't make sense to test the Mezzio components themselves - these are already thoroughly tested… It _does_ make sense to test your expectations of how the app is configured, and you can check the route result against expectations by inspecting the request, or the return value of the 'TestRouter' implementation.

**Comment by froschdesign** [comment]
A testing library for Mezzio is a great idea! But I also have the impression that testing is being too close to Mezzio because even internals are checked. I would make the tests and constraints independent of the framework and focus more on PSR, which means that I can use the testing library for Mezzio, Slim, etc. – interoperability also for testing.

**Comment by boesing** [comment]
I simply do not understand what would be the test idea in the example.

Can you probably provide all the context needed to get what the idea behind this is? To me, this looks like end-to-end testing, so you are basically testing if your application is configured correct.
If that is the case, why not just test it end-to-end without injecting a middleware/request handler/whatever? I do not get the whole point of this. If you have to add a middleware only for testing, you are basically not testing the real application but something only valid for testing.

Especially for PSR (which is immutable by design) you will not be able to retrieve i.e. the `RouteResult` from the test itself (unless you are using a non-immutable `Request` - which can be injected in your `Test` btw.

---

So if I understand correct, you might need something like (I wouldn't do it like that, as I do not like these weird state for the route but whatever floats your boat):

```php
<?php

final class MutableRequest implements \Psr\Http\Message\ServerRequestInterface
{
    // Make all the stuff mutable in here
    public function getRouteResult(): \Mezzio\Router\RouteResult|null
    {
        return $this->getAttribute(\Mezzio\Router\RouteResult::class);
    }
}

abstract class MezzioApplicationTestCase extends \PHPUnit\Framework\TestCase
{
    private \Mezzio\Router\RouteResult|null $route = null;

    protected function get(string $path): \Psr\Http\Message\ResponseInterface
    {
        $request = new MutableRequest($path);
        /** @var \Mezzio\Application $app */
        $app = $this->createApplication();
        $response = $app->handle($request);
        $this->route = $request->getRouteResult();

        return $response;
    }

    protected function assertMatchedRouteName(string $routeName): void
    {
        self::assertNotNull($this->route);
        self::assertSame($routeName, $this->route->getMatchedRouteName());
    }
}

final class ExampleTest extends MezzioApplicationTestCase
{
    public function testApplicationHandlesRequest(): void
    {
        $response = $this->get('/');
        self::assertSame(\Fig\Http\Message\StatusCodeInterface::STATUS_OK, $response->getStatusCode());
        $this->assertMatchedRouteName('home');
    }
}
```

But I simply do not see why one would have to replace the route, etc. with a middleware. Especially as you are unable to retrieve that from an immutable `RequestInterface`. I would not test the `run` method of `Application` but instead the `handle` method as that can retrieve an already created `RequestInterface` which can be mutable in your test szenario.

**Comment by ghostwriter** [comment]
> So, the point here is testing expectations - you expect the router to match a specific route and if it doesn't, there's a problem with your route configuration. Your wrapped `RouterInterface` will yield the `RouteResult` you expect _(hopefully)_. None of the middleware in the pipeline should alter the matched route - that would be very weird, so, because requests are immutable, you can be sure that the route result referenced in the request is what the router implementation returned. Instead of "newing" all these wrappers, wouldn't it be better to inject them into the testing framework in some way, so that users can say to the 'TestRouter' for example, `$testRouter->expectMatchedRouteName('foo')` prior to executing the pipeline? It doesn't make sense to test the Mezzio components themselves - these are already thoroughly tested… It _does_ make sense to test your expectations of how the app is configured, and you can check the route result against expectations by inspecting the request, or the return value of the 'TestRouter' implementation.
>
> _Originally posted by @gsteel in https://github.com/mezzio/mezzio-router/issues/74#issuecomment-2303280796_

i agree with your points about immutability, and using dependency injection (delegator factory).

i do not "expect" any thing, much like a spy it just sits in the middle and dispatches an event via psr14 Event Dispatcher from the mezzio-router, mezzio-template, psr7, psr11, psr15, psr17 and psr18 "delegator" classes each and ever behavior and action and dispatch an event before and after

eg.

- `with*()` calls on `Message` in between `Middleware`
- processing `Middleware`
- calling `has` and `get` on Container.
- when `Client` calls `sendRequest`
- when `Handler` calls `handle`

What method was called?
When was it called?
With what arguments was it called, if any?
What was the result?

the "Assertions" the user later writes in their test, would "register" listers for specific event, and preform those action defined in the listener.

eg. assertion are happening "in real time" as you navigate your website via eg. `http://localhost` in a dev env.

the idea came from reading from 

https://github.com/php/php-src/blob/master/sapi/cli/tests/php_cli_server.inc#L11

---

> A testing library for Mezzio is a great idea! But I also have the impression that testing is being too close to Mezzio because even internals are checked. I would make the tests and constraints independent of the framework and focus more on PSR, which means that I can use the testing library for Mezzio, Slim, etc. – interoperability also for testing.
>
> _Originally posted by @froschdesign in https://github.com/mezzio/mezzio-router/issues/74#issuecomment-2304052578_

I agree.

Realized that i'm overextending myself trying to cover mezzio-router and mezzio-template.

---

> I simply do not understand what would be the test idea in the example.
>
> Can you probably provide all the context needed to get what the idea behind this is? To me, this looks like end-to-end 
>
> testing, so you are basically testing if your application is configured correct.
> If that is the case, why not just test it end-to-end without injecting a middleware/request handler/whatever? I do not get the whole point of this. If you have to add a middleware only for testing, you are basically not testing the real application but something only valid for testing.
> 
> Especially for PSR (which is immutable by design) you will not be able to retrieve i.e. the `RouteResult` from the test itself (unless you are using a non-immutable `Request` - which can be injected in your `Test` btw.
> 
> ---
> 
> So if I understand correct, you might need something like (I wouldn't do it like that, as I do not like these weird state for the route but whatever floats your boat):
> 
> ```php
> <?php
> 
> final class MutableRequest implements \Psr\Http\Message\ServerRequestInterface
> {
>     // Make all the stuff mutable in here
>     public function getRouteResult(): \Mezzio\Router\RouteResult|null
>     {
>         return $this->getAttribute(\Mezzio\Router\RouteResult::class);
>     }
> }
> 
> abstract class MezzioApplicationTestCase extends \PHPUnit\Framework\TestCase
> {
>     private \Mezzio\Router\RouteResult|null $route = null;
> 
>     protected function get(string $path): \Psr\Http\Message\ResponseInterface
>     {
>         $request = new MutableRequest($path);
>         /** @var \Mezzio\Application $app */
>         $app = $this->createApplication();
>         $response = $app->handle($request);
>         $this->route = $request->getRouteResult();
> 
>         return $response;
>     }
> 
>     protected function assertMatchedRouteName(string $routeName): void
>     {
>         self::assertNotNull($this->route);
>         self::assertSame($routeName, $this->route->getMatchedRouteName());
>     }
> }
> 
> final class ExampleTest extends MezzioApplicationTestCase
> {
>     public function testApplicationHandlesRequest(): void
>     {
>         $response = $this->get('/');
>         self::assertSame(\Fig\Http\Message\StatusCodeInterface::STATUS_OK, $response->getStatusCode());
>         $this->assertMatchedRouteName('home');
>     }
> }
> ```
>
>
> But I simply do not see why one would have to replace the route, etc. with a middleware. Especially as you are unable to retrieve that from an immutable `RequestInterface`. I would not test the `run` method of `Application` but instead the `handle` method as that can retrieve an already created `RequestInterface` which can be mutable in your test szenario.
>
> _Originally posted by @boesing in https://github.com/mezzio/mezzio-router/issues/74#issuecomment-2304255186_

yes, it can be done that way.

I start a PHP development server with custom PHP code and using a custom psr18 client to send the request to the applications when an event is dispatched.

I got the idea after reading these:

https://github.com/php/php-src/blob/master/sapi/cli/tests/php_cli_server.inc#L11

https://github.com/php/php-src/blob/6351468a5e58ecf31824f8f68473de43958f5d0b/sapi/phpdbg/web-bootstrap.php#L23

![image](https://github.com/user-attachments/assets/cd8afffe-3803-428c-975c-09e25f6914c4)

---

Thank you all for the explanation and patience.

I’ll close this GitHub issue as it’s no longer within my scope of work.

Have a great weekend!
